import type {Config} from "stylelint";

const config: Config = {
    ignoreFiles: ["components/Ui/**"], // Ignore Ui components generated by UI-Thing.
    extends: ["stylelint-config-standard-scss", "stylelint-config-standard-vue/scss"],
    rules: {
        "color-named": "never",
        "at-rule-no-unknown": null,
        "at-rule-empty-line-before": null,
        "scss/at-rule-no-unknown": [
            true,
            {
                ignoreAtRules: ["tailwind"]
            }
        ]
    }
};

export default config;
